### ISSUE TITLE
wrong weights url

### ISSUE THREAD

**Issue by asch99** [StanfordMIMI/Comp2Comp#13]
The system tries to download the weights file from the wrong url, so it fails there and stops.
Furthermore, as it is right now the system redownloads the weights for every new run, which makes it slow and results in redundant copies of the same file.

Both are easily solved. in models.py/load_model():

        try:
            filename = Models.find_model_weights()
        except:
            #weights_file_name = wget.download("https://huggingface.co/stanfordmimi/stanford_abct_v0.0.1/blob/main/stanford_v0.0.1.h5", out=PREFERENCES.MODELS_DIR)
            weights_file_name = wget.download("https://huggingface.co/stanfordmimi/stanford_abct_v0.0.1/resolve/main/stanford_v0.0.1.h5", out=PREFERENCES.MODELS_DIR)

            logger.info("Downloading muscle/fat model from hugging face")
            # filename = os.path.join(
            #    PREFERENCES.MODELS_DIR, "{}.h5".format(self.model_name)
            # )
            filename = Models.find_model_weights()
        logger.info("Loading muscle/fat model from {}".format(filename))
        return load_model(filename)

**Comment by louisblankemeier** [comment]
Thanks for proposing this update! Do you mind submitting a pull request?

**Comment by asch99** [comment]
Sure. Done.

**Comment by louisblankemeier** [comment]
Thanks @asch99 , I put this in the PR, but get the following error when I test your fork.
<img width="729" alt="Screen Shot 2022-12-12 at 11 05 51 AM" src="https://user-images.githubusercontent.com/44588516/207132717-a65dfad7-c300-4c46-87dc-d550664ff6e5.png">

**Comment by louisblankemeier** [comment]
okay fixed a bug on the main branch. your try / except statement would be a nice addition now
